# Generated by Django 5.0.7 on 2024-07-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sequence_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
